### PR TITLE
Added the option to choose between every second and only when it get to 10 seconds

### PR DESCRIPTION
**Pull request by vkyamane**
I don't really know why the code started working after I set stuff to false at line 46 in timer.js, but now I'm happy that it works.
The html for disabling the checkboxes if another is selected seems to work fine, but needs further testing.

### CODE REVIEW

**Comment by MenesesPT** [comment]
Thank you for your contribution 😃 

I will test and if everything is working I will merge.

**Comment by vkyamane** [comment]
Thank you for checking it out.
One thing that I want to request if this code gets implemented, is to make it so the module remembers your last used settings in the menu, as I'm currently using it to set a 90s timer when there's combat, it can get somewhat annoying to manually set it to that every time.
I don't really have any clue on how to do that rn, but if I ever find out, I'll just open another pull request.

**Comment by MenesesPT** [comment]
I changed the checkboxes to a combobox which I believe it's better.
Also the same parameter on the createTimer can be used to set a point where the ticks start (Integer, not limited to the 10s), false to disable them altogether or true to always tick.
I haven't tested this thoroughly but would like to hear your feedback on the changes before making a new release since it was your idea.

On the topic of the module remembering the last used settings I believe it's a great idea, I will implement it soon. Also maybe there should be a default setting instead of the last used but that may complicate things a bit, I will talk with @Thedvdias (module co-author) to discuss the better option.

**Comment by vkyamane** [comment]
Currently the main issue, is that you can't "just" play the last 10 seconds, as aside from disabling it through the menu, the ticking will continue whether you choose to enable it or just the last 10 seconds.

**Comment by MenesesPT** [comment]
Thanks for your time testing.

Creating timers by calling the function directly can have the following options:
```JS
Timer.createTimer(15, "Hurry Up!", true);  //Ticks play every second
Timer.createTimer(15, "Hurry Up!", false); //Ticks don't get played ever
Timer.createTimer(15, "Hurry Up!", 5);     //Ticks play only in the last 5 seconds (the number here can be any integer)
```

I would appreciate if you could test it once more. Thanks

**Comment by vkyamane** [comment]
I haven't even thought about using a macro to set the timer in the first place, even though foundry is all about that, lol. This makes the module remembering your last used options to not be necessary at all, as it can be even faster using this new way.
Everything that I tested worked flawlessly,
I think that for my use case as of now, the module is perfect, thanks!
Only things left to do then, are to update the readme so it shows how you can use either the duration that the ticking starts, or true|false depending on whether you want the ticking to go throughout the duration of the timer or not at all, and the createStopwatch example, as it seems to need the privateTimer boolean before tickSound, which is different from how createTimer works.

**Pull request merged**
